# Generated by Django 4.2.3 on 2023-07-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='caategory',
            new_name='category',
        ),
    ]
